FROM nvcr.io/nvidia/isaac/nova_carter_bringup:release_3.2-aarch64

COPY build_depends.repos /autoware_nova_carter/build_depends.repos
COPY autoware_nova_carter_description /autoware_nova_carter/src/autoware_nova_carter_description
COPY autoware_nova_carter_interface /autoware_nova_carter/src/autoware_nova_carter_interface
COPY autoware_nova_carter_occupancy_grid /autoware_nova_carter/src/autoware_nova_carter_occupancy_grid
COPY autoware_nova_carter_sensing /autoware_nova_carter/src/autoware_nova_carter_sensing
COPY autoware_nova_carter_vehicle /autoware_nova_carter/src/autoware_nova_carter_vehicle

WORKDIR /autoware_nova_carter
RUN vcs import src < build_depends.repos

# Remove deprecated keys
RUN rm /etc/apt/sources.list.d/ros2.list
RUN rm /usr/share/keyrings/ros-archive-keyring.gpg

# Now add the ROS 2 apt repository to your system. First authorize our GPG key with apt.
RUN apt update --allow-releaseinfo-change && sudo apt install -y curl gnupg lsb-release
RUN curl -sSL https://raw.githubusercontent.com/ros/rosdistro/master/ros.key -o /usr/share/keyrings/ros-archive-keyring.gpg

# Then add the repository to your sources list.
RUN echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/ros-archive-keyring.gpg] http://packages.ros.org/ros2/ubuntu $(source /etc/os-release && echo $UBUNTU_CODENAME) main" | tee /etc/apt/sources.list.d/ros2.list > /dev/null

RUN source /opt/ros/humble/setup.bash \
    && apt-get update \
    && rosdep update \
    && rosdep install -ry --from-paths src --ignore-src --rosdistro $ROS_DISTRO \
    && colcon build --cmake-args \
        " -Wno-dev" \
        " --no-warn-unused-cli" \
        " -DCMAKE_BUILD_TYPE=Release" \
        --merge-install \
        --install-base /opt/autoware_nova_carter \
    && rm -rf build log

COPY .docker/ros_entrypoint.sh /ros_entrypoint.sh
ENTRYPOINT ["/ros_entrypoint.sh"]
CMD ["/bin/bash"]
